# Generated by Django 4.2.24 on 2025-09-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import input_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('youtube_url', models.URLField()),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('channel_title', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('source_audio', models.FileField(blank=True, upload_to=input_app.models.job_dir)),
                ('wav_audio', models.FileField(blank=True, upload_to=input_app.models.job_dir)),
                ('transcript_json', models.FileField(blank=True, upload_to=input_app.models.job_dir)),
                ('transcript_vtt', models.FileField(blank=True, upload_to=input_app.models.job_dir)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('segment_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
