# Generated by Django 4.2.24 on 2025-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed'), ('awaiting_transcription', 'Awaiting_transcription')], default='queued', max_length=32),
        ),
    ]
