# Generated by Django 4.2.24 on 2025-09-19 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_app', '0002_alter_transcriptionjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='step',
            field=models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed'), ('awaiting_transcription', 'Awaiting_transcription')], default='queued', max_length=32),
        ),
    ]
